/**
 * This class is generated by jOOQ
 */
package com.rapleaf.jack.test_project.database_1.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comments extends org.jooq.impl.TableImpl<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord> {

	private static final long serialVersionUID = 1270661931;

	/**
	 * The singleton instance of <code>jack_1.comments</code>
	 */
	public static final com.rapleaf.jack.test_project.database_1.jooq.tables.Comments COMMENTS = new com.rapleaf.jack.test_project.database_1.jooq.tables.Comments();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord> getRecordType() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord.class;
	}

	/**
	 * The column <code>jack_1.comments.id</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>jack_1.comments.content</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>jack_1.comments.commenter_id</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, java.lang.Integer> COMMENTER_ID = createField("commenter_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>jack_1.comments.commented_on_id</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, java.lang.Long> COMMENTED_ON_ID = createField("commented_on_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>jack_1.comments.created_at</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>jack_1.comments</code> table reference
	 */
	public Comments() {
		this("comments", null);
	}

	/**
	 * Create an aliased <code>jack_1.comments</code> table reference
	 */
	public Comments(java.lang.String alias) {
		this(alias, com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS);
	}

	private Comments(java.lang.String alias, org.jooq.Table<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Comments(java.lang.String alias, org.jooq.Table<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.rapleaf.jack.test_project.database_1.jooq.Jack_1.JACK_1, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, java.lang.Integer> getIdentity() {
		return com.rapleaf.jack.test_project.database_1.jooq.Keys.IDENTITY_COMMENTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord> getPrimaryKey() {
		return com.rapleaf.jack.test_project.database_1.jooq.Keys.KEY_COMMENTS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord>>asList(com.rapleaf.jack.test_project.database_1.jooq.Keys.KEY_COMMENTS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, ?>>asList(com.rapleaf.jack.test_project.database_1.jooq.Keys.COMMENTS_COMMENTER_ID_FK, com.rapleaf.jack.test_project.database_1.jooq.Keys.COMMENTS_COMMENTED_ON_ID_FK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.rapleaf.jack.test_project.database_1.jooq.tables.Comments as(java.lang.String alias) {
		return new com.rapleaf.jack.test_project.database_1.jooq.tables.Comments(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.rapleaf.jack.test_project.database_1.jooq.tables.Comments rename(java.lang.String name) {
		return new com.rapleaf.jack.test_project.database_1.jooq.tables.Comments(name, null);
	}
}
