/**
 * This class is generated by jOOQ
 */
package com.rapleaf.jack.test_project.database_1.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Images extends org.jooq.impl.TableImpl<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord> {

	private static final long serialVersionUID = 606935633;

	/**
	 * The singleton instance of <code>jack_1.images</code>
	 */
	public static final com.rapleaf.jack.test_project.database_1.jooq.tables.Images IMAGES = new com.rapleaf.jack.test_project.database_1.jooq.tables.Images();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord> getRecordType() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord.class;
	}

	/**
	 * The column <code>jack_1.images.id</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>jack_1.images.user_id</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>jack_1.images</code> table reference
	 */
	public Images() {
		this("images", null);
	}

	/**
	 * Create an aliased <code>jack_1.images</code> table reference
	 */
	public Images(java.lang.String alias) {
		this(alias, com.rapleaf.jack.test_project.database_1.jooq.tables.Images.IMAGES);
	}

	private Images(java.lang.String alias, org.jooq.Table<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Images(java.lang.String alias, org.jooq.Table<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.rapleaf.jack.test_project.database_1.jooq.Jack_1.JACK_1, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord, java.lang.Integer> getIdentity() {
		return com.rapleaf.jack.test_project.database_1.jooq.Keys.IDENTITY_IMAGES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord> getPrimaryKey() {
		return com.rapleaf.jack.test_project.database_1.jooq.Keys.KEY_IMAGES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord>>asList(com.rapleaf.jack.test_project.database_1.jooq.Keys.KEY_IMAGES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord, ?>>asList(com.rapleaf.jack.test_project.database_1.jooq.Keys.IMAGES_USER_ID_FK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.rapleaf.jack.test_project.database_1.jooq.tables.Images as(java.lang.String alias) {
		return new com.rapleaf.jack.test_project.database_1.jooq.tables.Images(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.rapleaf.jack.test_project.database_1.jooq.tables.Images rename(java.lang.String name) {
		return new com.rapleaf.jack.test_project.database_1.jooq.tables.Images(name, null);
	}
}
