/**
 * This class is generated by jOOQ
 */
package com.rapleaf.jack.test_project.database_1.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Posts extends org.jooq.impl.TableImpl<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord> {

	private static final long serialVersionUID = -1633572631;

	/**
	 * The singleton instance of <code>jack_1.posts</code>
	 */
	public static final com.rapleaf.jack.test_project.database_1.jooq.tables.Posts POSTS = new com.rapleaf.jack.test_project.database_1.jooq.tables.Posts();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord> getRecordType() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord.class;
	}

	/**
	 * The column <code>jack_1.posts.id</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>jack_1.posts.title</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>jack_1.posts.posted_at_millis</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord, java.sql.Date> POSTED_AT_MILLIS = createField("posted_at_millis", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>jack_1.posts.user_id</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>jack_1.posts.updated_at</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord, java.sql.Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>jack_1.posts</code> table reference
	 */
	public Posts() {
		this("posts", null);
	}

	/**
	 * Create an aliased <code>jack_1.posts</code> table reference
	 */
	public Posts(java.lang.String alias) {
		this(alias, com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS);
	}

	private Posts(java.lang.String alias, org.jooq.Table<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Posts(java.lang.String alias, org.jooq.Table<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.rapleaf.jack.test_project.database_1.jooq.Jack_1.JACK_1, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord, java.lang.Long> getIdentity() {
		return com.rapleaf.jack.test_project.database_1.jooq.Keys.IDENTITY_POSTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord> getPrimaryKey() {
		return com.rapleaf.jack.test_project.database_1.jooq.Keys.KEY_POSTS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord>>asList(com.rapleaf.jack.test_project.database_1.jooq.Keys.KEY_POSTS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord, ?>>asList(com.rapleaf.jack.test_project.database_1.jooq.Keys.POSTS_USER_ID_FK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.rapleaf.jack.test_project.database_1.jooq.tables.Posts as(java.lang.String alias) {
		return new com.rapleaf.jack.test_project.database_1.jooq.tables.Posts(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.rapleaf.jack.test_project.database_1.jooq.tables.Posts rename(java.lang.String name) {
		return new com.rapleaf.jack.test_project.database_1.jooq.tables.Posts(name, null);
	}
}
