/**
 * This class is generated by jOOQ
 */
package com.rapleaf.jack.test_project.database_1.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaMigrations extends org.jooq.impl.TableImpl<com.rapleaf.jack.test_project.database_1.jooq.tables.records.SchemaMigrationsRecord> {

	private static final long serialVersionUID = 1912426878;

	/**
	 * The singleton instance of <code>jack_1.schema_migrations</code>
	 */
	public static final com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations SCHEMA_MIGRATIONS = new com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.rapleaf.jack.test_project.database_1.jooq.tables.records.SchemaMigrationsRecord> getRecordType() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.records.SchemaMigrationsRecord.class;
	}

	/**
	 * The column <code>jack_1.schema_migrations.version</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.SchemaMigrationsRecord, java.lang.String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>jack_1.schema_migrations</code> table reference
	 */
	public SchemaMigrations() {
		this("schema_migrations", null);
	}

	/**
	 * Create an aliased <code>jack_1.schema_migrations</code> table reference
	 */
	public SchemaMigrations(java.lang.String alias) {
		this(alias, com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations.SCHEMA_MIGRATIONS);
	}

	private SchemaMigrations(java.lang.String alias, org.jooq.Table<com.rapleaf.jack.test_project.database_1.jooq.tables.records.SchemaMigrationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private SchemaMigrations(java.lang.String alias, org.jooq.Table<com.rapleaf.jack.test_project.database_1.jooq.tables.records.SchemaMigrationsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.rapleaf.jack.test_project.database_1.jooq.Jack_1.JACK_1, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.SchemaMigrationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.SchemaMigrationsRecord>>asList(com.rapleaf.jack.test_project.database_1.jooq.Keys.KEY_SCHEMA_MIGRATIONS_UNIQUE_SCHEMA_MIGRATIONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations as(java.lang.String alias) {
		return new com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations rename(java.lang.String name) {
		return new com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations(name, null);
	}
}
