/**
 * This class is generated by jOOQ
 */
package com.rapleaf.jack.test_project.database_1.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends org.jooq.impl.TableImpl<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> {

	private static final long serialVersionUID = -1089488662;

	/**
	 * The singleton instance of <code>jack_1.users</code>
	 */
	public static final com.rapleaf.jack.test_project.database_1.jooq.tables.Users USERS = new com.rapleaf.jack.test_project.database_1.jooq.tables.Users();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> getRecordType() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord.class;
	}

	/**
	 * The column <code>jack_1.users.id</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>jack_1.users.handle</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, java.lang.String> HANDLE = createField("handle", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>jack_1.users.created_at_millis</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, java.lang.Long> CREATED_AT_MILLIS = createField("created_at_millis", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>jack_1.users.num_posts</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, java.lang.Integer> NUM_POSTS = createField("num_posts", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>jack_1.users.some_date</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, java.sql.Date> SOME_DATE = createField("some_date", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>jack_1.users.some_datetime</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, java.sql.Timestamp> SOME_DATETIME = createField("some_datetime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>jack_1.users.bio</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, java.lang.String> BIO = createField("bio", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>jack_1.users.some_binary</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, byte[]> SOME_BINARY = createField("some_binary", org.jooq.impl.SQLDataType.BLOB.length(65535), this, "");

	/**
	 * The column <code>jack_1.users.some_float</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, java.lang.Double> SOME_FLOAT = createField("some_float", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>jack_1.users.some_decimal</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, java.math.BigDecimal> SOME_DECIMAL = createField("some_decimal", org.jooq.impl.SQLDataType.DECIMAL.precision(20, 10), this, "");

	/**
	 * The column <code>jack_1.users.some_boolean</code>.
	 */
	public final org.jooq.TableField<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, java.lang.Byte> SOME_BOOLEAN = createField("some_boolean", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * Create a <code>jack_1.users</code> table reference
	 */
	public Users() {
		this("users", null);
	}

	/**
	 * Create an aliased <code>jack_1.users</code> table reference
	 */
	public Users(java.lang.String alias) {
		this(alias, com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS);
	}

	private Users(java.lang.String alias, org.jooq.Table<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Users(java.lang.String alias, org.jooq.Table<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.rapleaf.jack.test_project.database_1.jooq.Jack_1.JACK_1, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, java.lang.Integer> getIdentity() {
		return com.rapleaf.jack.test_project.database_1.jooq.Keys.IDENTITY_USERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> getPrimaryKey() {
		return com.rapleaf.jack.test_project.database_1.jooq.Keys.KEY_USERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord>>asList(com.rapleaf.jack.test_project.database_1.jooq.Keys.KEY_USERS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.rapleaf.jack.test_project.database_1.jooq.tables.Users as(java.lang.String alias) {
		return new com.rapleaf.jack.test_project.database_1.jooq.tables.Users(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.rapleaf.jack.test_project.database_1.jooq.tables.Users rename(java.lang.String name) {
		return new com.rapleaf.jack.test_project.database_1.jooq.tables.Users(name, null);
	}
}
