/**
 * This class is generated by jOOQ
 */
package com.rapleaf.jack.test_project.database_1.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentsRecord extends org.jooq.impl.UpdatableRecordImpl<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Long, java.sql.Timestamp> {

	private static final long serialVersionUID = -1838220212;

	/**
	 * Setter for <code>jack_1.comments.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jack_1.comments.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>jack_1.comments.content</code>.
	 */
	public void setContent(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jack_1.comments.content</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>jack_1.comments.commenter_id</code>.
	 */
	public void setCommenterId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jack_1.comments.commenter_id</code>.
	 */
	public java.lang.Integer getCommenterId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>jack_1.comments.commented_on_id</code>.
	 */
	public void setCommentedOnId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>jack_1.comments.commented_on_id</code>.
	 */
	public java.lang.Long getCommentedOnId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>jack_1.comments.created_at</code>.
	 */
	public void setCreatedAt(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>jack_1.comments.created_at</code>.
	 */
	public java.sql.Timestamp getCreatedAt() {
		return (java.sql.Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Long, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Long, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS.COMMENTER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS.COMMENTED_ON_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getCommenterId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getCommentedOnId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommentsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommentsRecord value2(java.lang.String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommentsRecord value3(java.lang.Integer value) {
		setCommenterId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommentsRecord value4(java.lang.Long value) {
		setCommentedOnId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommentsRecord value5(java.sql.Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CommentsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.Long value4, java.sql.Timestamp value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CommentsRecord
	 */
	public CommentsRecord() {
		super(com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS);
	}

	/**
	 * Create a detached, initialised CommentsRecord
	 */
	public CommentsRecord(java.lang.Integer id, java.lang.String content, java.lang.Integer commenterId, java.lang.Long commentedOnId, java.sql.Timestamp createdAt) {
		super(com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS);

		setValue(0, id);
		setValue(1, content);
		setValue(2, commenterId);
		setValue(3, commentedOnId);
		setValue(4, createdAt);
	}
}
