/**
 * This class is generated by jOOQ
 */
package com.rapleaf.jack.test_project.database_1.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostsRecord extends org.jooq.impl.UpdatableRecordImpl<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord> implements org.jooq.Record5<java.lang.Long, java.lang.String, java.sql.Date, java.lang.Integer, java.sql.Timestamp> {

	private static final long serialVersionUID = -1213706019;

	/**
	 * Setter for <code>jack_1.posts.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jack_1.posts.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>jack_1.posts.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jack_1.posts.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>jack_1.posts.posted_at_millis</code>.
	 */
	public void setPostedAtMillis(java.sql.Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jack_1.posts.posted_at_millis</code>.
	 */
	public java.sql.Date getPostedAtMillis() {
		return (java.sql.Date) getValue(2);
	}

	/**
	 * Setter for <code>jack_1.posts.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>jack_1.posts.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>jack_1.posts.updated_at</code>.
	 */
	public void setUpdatedAt(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>jack_1.posts.updated_at</code>.
	 */
	public java.sql.Timestamp getUpdatedAt() {
		return (java.sql.Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.sql.Date, java.lang.Integer, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.sql.Date, java.lang.Integer, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field3() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS.POSTED_AT_MILLIS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS.UPDATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value3() {
		return getPostedAtMillis();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getUpdatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostsRecord value2(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostsRecord value3(java.sql.Date value) {
		setPostedAtMillis(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostsRecord value4(java.lang.Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostsRecord value5(java.sql.Timestamp value) {
		setUpdatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostsRecord values(java.lang.Long value1, java.lang.String value2, java.sql.Date value3, java.lang.Integer value4, java.sql.Timestamp value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PostsRecord
	 */
	public PostsRecord() {
		super(com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS);
	}

	/**
	 * Create a detached, initialised PostsRecord
	 */
	public PostsRecord(java.lang.Long id, java.lang.String title, java.sql.Date postedAtMillis, java.lang.Integer userId, java.sql.Timestamp updatedAt) {
		super(com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS);

		setValue(0, id);
		setValue(1, title);
		setValue(2, postedAtMillis);
		setValue(3, userId);
		setValue(4, updatedAt);
	}
}
