/**
 * This class is generated by jOOQ
 */
package com.rapleaf.jack.test_project.database_1.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaMigrationsRecord extends org.jooq.impl.TableRecordImpl<com.rapleaf.jack.test_project.database_1.jooq.tables.records.SchemaMigrationsRecord> implements org.jooq.Record1<java.lang.String> {

	private static final long serialVersionUID = 2015423974;

	/**
	 * Setter for <code>jack_1.schema_migrations.version</code>.
	 */
	public void setVersion(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jack_1.schema_migrations.version</code>.
	 */
	public java.lang.String getVersion() {
		return (java.lang.String) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> fieldsRow() {
		return (org.jooq.Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> valuesRow() {
		return (org.jooq.Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations.SCHEMA_MIGRATIONS.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemaMigrationsRecord value1(java.lang.String value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemaMigrationsRecord values(java.lang.String value1) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SchemaMigrationsRecord
	 */
	public SchemaMigrationsRecord() {
		super(com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations.SCHEMA_MIGRATIONS);
	}

	/**
	 * Create a detached, initialised SchemaMigrationsRecord
	 */
	public SchemaMigrationsRecord(java.lang.String version) {
		super(com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations.SCHEMA_MIGRATIONS);

		setValue(0, version);
	}
}
