/**
 * This class is generated by jOOQ
 */
package com.rapleaf.jack.test_project.database_1.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends org.jooq.impl.UpdatableRecordImpl<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> implements org.jooq.Record11<java.lang.Integer, java.lang.String, java.lang.Long, java.lang.Integer, java.sql.Date, java.sql.Timestamp, java.lang.String, byte[], java.lang.Double, java.math.BigDecimal, java.lang.Byte> {

	private static final long serialVersionUID = 842883326;

	/**
	 * Setter for <code>jack_1.users.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jack_1.users.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>jack_1.users.handle</code>.
	 */
	public void setHandle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jack_1.users.handle</code>.
	 */
	public java.lang.String getHandle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>jack_1.users.created_at_millis</code>.
	 */
	public void setCreatedAtMillis(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jack_1.users.created_at_millis</code>.
	 */
	public java.lang.Long getCreatedAtMillis() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>jack_1.users.num_posts</code>.
	 */
	public void setNumPosts(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>jack_1.users.num_posts</code>.
	 */
	public java.lang.Integer getNumPosts() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>jack_1.users.some_date</code>.
	 */
	public void setSomeDate(java.sql.Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>jack_1.users.some_date</code>.
	 */
	public java.sql.Date getSomeDate() {
		return (java.sql.Date) getValue(4);
	}

	/**
	 * Setter for <code>jack_1.users.some_datetime</code>.
	 */
	public void setSomeDatetime(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>jack_1.users.some_datetime</code>.
	 */
	public java.sql.Timestamp getSomeDatetime() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>jack_1.users.bio</code>.
	 */
	public void setBio(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>jack_1.users.bio</code>.
	 */
	public java.lang.String getBio() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>jack_1.users.some_binary</code>.
	 */
	public void setSomeBinary(byte[] value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>jack_1.users.some_binary</code>.
	 */
	public byte[] getSomeBinary() {
		return (byte[]) getValue(7);
	}

	/**
	 * Setter for <code>jack_1.users.some_float</code>.
	 */
	public void setSomeFloat(java.lang.Double value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>jack_1.users.some_float</code>.
	 */
	public java.lang.Double getSomeFloat() {
		return (java.lang.Double) getValue(8);
	}

	/**
	 * Setter for <code>jack_1.users.some_decimal</code>.
	 */
	public void setSomeDecimal(java.math.BigDecimal value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>jack_1.users.some_decimal</code>.
	 */
	public java.math.BigDecimal getSomeDecimal() {
		return (java.math.BigDecimal) getValue(9);
	}

	/**
	 * Setter for <code>jack_1.users.some_boolean</code>.
	 */
	public void setSomeBoolean(java.lang.Byte value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>jack_1.users.some_boolean</code>.
	 */
	public java.lang.Byte getSomeBoolean() {
		return (java.lang.Byte) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.lang.String, java.lang.Long, java.lang.Integer, java.sql.Date, java.sql.Timestamp, java.lang.String, byte[], java.lang.Double, java.math.BigDecimal, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.lang.String, java.lang.Long, java.lang.Integer, java.sql.Date, java.sql.Timestamp, java.lang.String, byte[], java.lang.Double, java.math.BigDecimal, java.lang.Byte> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS.HANDLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS.CREATED_AT_MILLIS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS.NUM_POSTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field5() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS.SOME_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS.SOME_DATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS.BIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field8() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS.SOME_BINARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field9() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS.SOME_FLOAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field10() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS.SOME_DECIMAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field11() {
		return com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS.SOME_BOOLEAN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getHandle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getCreatedAtMillis();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getNumPosts();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value5() {
		return getSomeDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getSomeDatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getBio();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value8() {
		return getSomeBinary();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value9() {
		return getSomeFloat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value10() {
		return getSomeDecimal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value11() {
		return getSomeBoolean();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value2(java.lang.String value) {
		setHandle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value3(java.lang.Long value) {
		setCreatedAtMillis(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value4(java.lang.Integer value) {
		setNumPosts(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value5(java.sql.Date value) {
		setSomeDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value6(java.sql.Timestamp value) {
		setSomeDatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value7(java.lang.String value) {
		setBio(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value8(byte[] value) {
		setSomeBinary(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value9(java.lang.Double value) {
		setSomeFloat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value10(java.math.BigDecimal value) {
		setSomeDecimal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value11(java.lang.Byte value) {
		setSomeBoolean(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Long value3, java.lang.Integer value4, java.sql.Date value5, java.sql.Timestamp value6, java.lang.String value7, byte[] value8, java.lang.Double value9, java.math.BigDecimal value10, java.lang.Byte value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS);
	}

	/**
	 * Create a detached, initialised UsersRecord
	 */
	public UsersRecord(java.lang.Integer id, java.lang.String handle, java.lang.Long createdAtMillis, java.lang.Integer numPosts, java.sql.Date someDate, java.sql.Timestamp someDatetime, java.lang.String bio, byte[] someBinary, java.lang.Double someFloat, java.math.BigDecimal someDecimal, java.lang.Byte someBoolean) {
		super(com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS);

		setValue(0, id);
		setValue(1, handle);
		setValue(2, createdAtMillis);
		setValue(3, numPosts);
		setValue(4, someDate);
		setValue(5, someDatetime);
		setValue(6, bio);
		setValue(7, someBinary);
		setValue(8, someFloat);
		setValue(9, someDecimal);
		setValue(10, someBoolean);
	}
}
