/**
 * This class is generated by jOOQ
 */
package com.rapleaf.jack.test_project.database_1.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>jack_1</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, java.lang.Integer> IDENTITY_COMMENTS = Identities0.IDENTITY_COMMENTS;
	public static final org.jooq.Identity<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord, java.lang.Integer> IDENTITY_IMAGES = Identities0.IDENTITY_IMAGES;
	public static final org.jooq.Identity<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord, java.lang.Long> IDENTITY_POSTS = Identities0.IDENTITY_POSTS;
	public static final org.jooq.Identity<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, java.lang.Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord> KEY_COMMENTS_PRIMARY = UniqueKeys0.KEY_COMMENTS_PRIMARY;
	public static final org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord> KEY_IMAGES_PRIMARY = UniqueKeys0.KEY_IMAGES_PRIMARY;
	public static final org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord> KEY_POSTS_PRIMARY = UniqueKeys0.KEY_POSTS_PRIMARY;
	public static final org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.SchemaMigrationsRecord> KEY_SCHEMA_MIGRATIONS_UNIQUE_SCHEMA_MIGRATIONS = UniqueKeys0.KEY_SCHEMA_MIGRATIONS_UNIQUE_SCHEMA_MIGRATIONS;
	public static final org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> COMMENTS_COMMENTER_ID_FK = ForeignKeys0.COMMENTS_COMMENTER_ID_FK;
	public static final org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord> COMMENTS_COMMENTED_ON_ID_FK = ForeignKeys0.COMMENTS_COMMENTED_ON_ID_FK;
	public static final org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord, com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> IMAGES_USER_ID_FK = ForeignKeys0.IMAGES_USER_ID_FK;
	public static final org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord, com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> POSTS_USER_ID_FK = ForeignKeys0.POSTS_USER_ID_FK;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, java.lang.Integer> IDENTITY_COMMENTS = createIdentity(com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS, com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS.ID);
		public static org.jooq.Identity<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord, java.lang.Integer> IDENTITY_IMAGES = createIdentity(com.rapleaf.jack.test_project.database_1.jooq.tables.Images.IMAGES, com.rapleaf.jack.test_project.database_1.jooq.tables.Images.IMAGES.ID);
		public static org.jooq.Identity<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord, java.lang.Long> IDENTITY_POSTS = createIdentity(com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS, com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS.ID);
		public static org.jooq.Identity<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord, java.lang.Integer> IDENTITY_USERS = createIdentity(com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS, com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord> KEY_COMMENTS_PRIMARY = createUniqueKey(com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS, com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS.ID);
		public static final org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord> KEY_IMAGES_PRIMARY = createUniqueKey(com.rapleaf.jack.test_project.database_1.jooq.tables.Images.IMAGES, com.rapleaf.jack.test_project.database_1.jooq.tables.Images.IMAGES.ID);
		public static final org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord> KEY_POSTS_PRIMARY = createUniqueKey(com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS, com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS.ID);
		public static final org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.SchemaMigrationsRecord> KEY_SCHEMA_MIGRATIONS_UNIQUE_SCHEMA_MIGRATIONS = createUniqueKey(com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations.SCHEMA_MIGRATIONS, com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations.SCHEMA_MIGRATIONS.VERSION);
		public static final org.jooq.UniqueKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> KEY_USERS_PRIMARY = createUniqueKey(com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS, com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> COMMENTS_COMMENTER_ID_FK = createForeignKey(com.rapleaf.jack.test_project.database_1.jooq.Keys.KEY_USERS_PRIMARY, com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS, com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS.COMMENTER_ID);
		public static final org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.CommentsRecord, com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord> COMMENTS_COMMENTED_ON_ID_FK = createForeignKey(com.rapleaf.jack.test_project.database_1.jooq.Keys.KEY_POSTS_PRIMARY, com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS, com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS.COMMENTED_ON_ID);
		public static final org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.ImagesRecord, com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> IMAGES_USER_ID_FK = createForeignKey(com.rapleaf.jack.test_project.database_1.jooq.Keys.KEY_USERS_PRIMARY, com.rapleaf.jack.test_project.database_1.jooq.tables.Images.IMAGES, com.rapleaf.jack.test_project.database_1.jooq.tables.Images.IMAGES.USER_ID);
		public static final org.jooq.ForeignKey<com.rapleaf.jack.test_project.database_1.jooq.tables.records.PostsRecord, com.rapleaf.jack.test_project.database_1.jooq.tables.records.UsersRecord> POSTS_USER_ID_FK = createForeignKey(com.rapleaf.jack.test_project.database_1.jooq.Keys.KEY_USERS_PRIMARY, com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS, com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS.USER_ID);
	}
}
