/**
 * This class is generated by jOOQ
 */
package com.rapleaf.jack.test_project.database_1.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in jack_1
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table jack_1.comments
	 */
	public static final com.rapleaf.jack.test_project.database_1.jooq.tables.Comments COMMENTS = com.rapleaf.jack.test_project.database_1.jooq.tables.Comments.COMMENTS;

	/**
	 * The table jack_1.images
	 */
	public static final com.rapleaf.jack.test_project.database_1.jooq.tables.Images IMAGES = com.rapleaf.jack.test_project.database_1.jooq.tables.Images.IMAGES;

	/**
	 * The table jack_1.posts
	 */
	public static final com.rapleaf.jack.test_project.database_1.jooq.tables.Posts POSTS = com.rapleaf.jack.test_project.database_1.jooq.tables.Posts.POSTS;

	/**
	 * The table jack_1.schema_migrations
	 */
	public static final com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations SCHEMA_MIGRATIONS = com.rapleaf.jack.test_project.database_1.jooq.tables.SchemaMigrations.SCHEMA_MIGRATIONS;

	/**
	 * The table jack_1.users
	 */
	public static final com.rapleaf.jack.test_project.database_1.jooq.tables.Users USERS = com.rapleaf.jack.test_project.database_1.jooq.tables.Users.USERS;
}
